#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configuring HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  mkwebdesign-frontend
        bind *:80
        mode http
        default_backend mkwebdesign-backend
backend mkwebdesign-backend
        balance roundrobin
        server 320353-web-01 100.25.179.31:80 check
        server 320353-web-02 54.237.87.213:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
