#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
#setting up the SSH-agent
eval $("ssh-agent")
# path to IdentityFile
ssh-add ~/.ssh/school
# username and IP Address
ssh ubuntu@100.25.190.57
