#!/usr/bin/env bash
# "Best School" is displayed  10 times
IFS=':'

while read -r usr pswd uid gid uinfo hd csh
do
	echo "The user $usr is part of the $gid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pswd, more info about the user here: $uinfo"
done < /etc/passwd

